# -*- coding: utf-8 -*-
"""swotproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhJFNKMEBA4EfR3X1p_SySMgxE_W1Wvw

**Выполнила: Безрукова Ольга Дмитриевна 20БИ2**

**Описание бизнес-проекта:** открытие детского развивающего центра, где предлагаются кружки для детей от 4-5 лет (дошкольное образование, лепка, рисование). Набор в небольшие группы. Помещение: аренда небольшой студии с приемной, 2 комнатами и санузлом. Сотрудники: 2-3 преподавателя, уборщица.
"""

!ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
!date

# Commented out IPython magic to ensure Python compatibility.
import gspread
import os

from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

from google.colab import drive
drive.mount('/content/drive')

print('\n', os.listdir('/content/drive/MyDrive/Colab Notebooks/swot'))
# %ll -lF /content/drive/MyDrive/"Colab Notebooks"/swot/

from oauth2client.client import GoogleCredentials
gs = gspread.authorize(GoogleCredentials.get_application_default())

table = gs.open_by_key('1QgImMw5r5tYzNvcHo86sOc6Iqk6MIxDHzKQV4LIi2do')
print('\n', table.worksheets())

!ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
print('\n')

import matplotlib.pyplot as plt

worksheet = table.worksheet("Strengths")
rows = worksheet.get_all_values()
str_name = list()
str_importance = list()
str_probability = list()
str_power = list()

i = 0
for row in rows:
  if (i>2):
    str_name.append(row[0])
    str_importance.append(int(row[2]))
    str_probability.append(float(row[3]))
    str_power.append(int(row[2])*float(row[3]))
  i+=1
print('\n', str_name, str_importance, str_probability, str_power, sep='\n', end='\n\n')

cell_list = worksheet.range('E4:E8')
i = 0
for cell in cell_list:
    cell.value = str_power[i]
    i+=1

worksheet.update_cells(cell_list)

labels = ['1', '2', '3', '4', '5']
plt.ylabel("Мощность воздействия")
plt.xlabel("Обозначения:")
plt.title("Strengths:")
plt.bar(labels, str_power)
plt.grid(axis = 'y', linestyle = '--')
plt.show()
for i in range(str_name.__len__()):
        print(i+1, " - ", str_name[i])
        i += 1

worksheet = table.worksheet("Weaknesses")
rows = worksheet.get_all_values()
weak_name = list()
weak_importance = list()
weak_probability = list()
weak_power = list()

i = 0
for row in rows:
  if (i>2):
    weak_name.append(row[0])
    weak_importance.append(int(row[2]))
    weak_probability.append(float(row[3]))
    weak_power.append(int(row[2])*float(row[3]))
  i+=1
print('\n', weak_name, weak_importance, weak_probability, weak_power, sep='\n', end='\n\n')

cell_list = worksheet.range('E4:E8')
i = 0
for cell in cell_list:
    cell.value = weak_power[i]
    i+=1

worksheet.update_cells(cell_list)

labels = ['1', '2', '3', '4', '5']
plt.ylabel("Мощность воздействия")
plt.xlabel("Обозначения:")
plt.title("Weaknesses:")
plt.bar(labels, weak_power)
plt.grid(axis = 'y', linestyle = '--')
plt.show()
for i in range(weak_name.__len__()):
        print(i+1, " - ", weak_name[i])
        i += 1

worksheet = table.worksheet("Opportunities")
rows = worksheet.get_all_values()
opp_name = list()
opp_importance = list()
opp_probability = list()
opp_power = list()

i = 0
for row in rows:
  if (i>2):
    opp_name.append(row[0])
    opp_importance.append(int(row[2]))
    opp_probability.append(float(row[3]))
    opp_power.append(int(row[2])*float(row[3]))  
  i+=1
print('\n', opp_name, opp_importance, opp_probability, opp_power, sep='\n', end='\n\n')

cell_list = worksheet.range('E4:E8')
i = 0
for cell in cell_list:
    cell.value = opp_power[i]
    i+=1
worksheet.update_cells(cell_list)

labels = ['1', '2', '3', '4', '5']
plt.ylabel("Мощность воздействия")
plt.xlabel("Обозначения:")
plt.title("Opportunities:")
plt.bar(labels, opp_power)
plt.grid(axis = 'y', linestyle = '--')
plt.show()
for i in range(opp_name.__len__()):
        print(i+1, " - ", opp_name[i])
        i += 1

worksheet = table.worksheet("Threats")
rows = worksheet.get_all_values()
thr_name = list()
thr_importance = list()
thr_probability = list()
thr_power = list()

i = 0
for row in rows:
  if (i>2):
    thr_name.append(row[0])
    thr_importance.append(int(row[2]))
    thr_probability.append(float(row[3]))
    thr_power.append(int(row[2])*float(row[3]))    
  i+=1
print('\n', thr_name, thr_importance, thr_probability, thr_power, sep='\n', end='\n\n')

cell_list = worksheet.range('E4:E8')
i = 0
for cell in cell_list:
    cell.value = thr_power[i]
    i+=1

worksheet.update_cells(cell_list)

labels = ['1', '2', '3', '4', '5']
plt.ylabel("Мощность воздействия")
plt.xlabel("Обозначения:")
plt.title("Threats:")
plt.bar(labels, thr_power)
plt.grid(axis = 'y', linestyle = '--')
plt.show()
for i in range(thr_name.__len__()):
        print(i+1, " - ", thr_name[i])
        i += 1

worksheet = table.worksheet("Result")
worksheet.update_acell('B2', sum(str_power))
worksheet.update_acell('C2', sum(weak_power))
worksheet.update_acell('D2', sum(opp_power))
worksheet.update_acell('E2', sum(thr_power))
result = sum(str_power) - sum(weak_power) + sum(opp_power) - sum(thr_power)
worksheet.update_acell('F2', result)

print('\n', "Strength:",  sum(str_power))
print('\n', "Weaknesses:",  sum(weak_power))
print('\n', "Opportunities:",  sum(opp_power))
print('\n', "Threats:",  sum(thr_power))
print('\n', "Result:",  result, end='\n')

import numpy as np
labels = ['1', '2', '3', '4', '5']
name = ['Strengths', 'Weaknesses', 'Opportunities', 'Threats', 'Result']
power = [sum(str_power), -sum(weak_power), sum(opp_power), -sum(thr_power), result]
plt.ylabel("Мощность воздействия")
plt.xlabel("Обозначения:")
plt.title("Swot:")
plt.bar(labels, power)
plt.grid(axis = 'y', linestyle = '--')
plt.yticks(np.arange(-30, 35, step=5))
plt.show()
for i in range(name.__len__()):
        print(i+1, " - ", name[i])
        i += 1
        
print('\n')
!date